const $ = '/assets/avatars/';

export const AVATARS = [
  `${$}black-square.jpeg`,
  `${$}buttercup.jpeg`,
  `${$}c3po.jpeg`,
  `${$}ching-shih.jpeg`,
  `${$}default.png`,
  `${$}galaxy.jpg`,
  `${$}gaston.jpg`,
  `${$}green-square.png`,
  `${$}heihachi.jpeg`,
  `${$}hypatia.jpeg`,
  `${$}kiwi.jpg`,
  `${$}magica.jpg`,
  `${$}marjory.jpg`,
  `${$}max-headroom.jpg`,
  `${$}megatron.jpeg`,
  `${$}monster.png`,
  `${$}muttley.jpg`,
  `${$}ocean.jpeg`,
  `${$}pizza-rat.jpg`,
  `${$}red-yarn.jpg`,
  `${$}sailboat.jpg`,
  `${$}samurai.jpg`,
  `${$}saul.jpg`,
  `${$}sauron.jpg`,
  `${$}skeletor.jpeg`,
  `${$}slimer.jpg`,
  `${$}xena.jpg`,
]
